config/routes.rb
Rails.application.routes.draw do
  resources :controllers
  mount ActionCable.server, at: '/cable'  
  resources :chatrooms do 
    resource :chatroom_users
    resources :chatroom_messages

  end
  get 'pages/_profile'

  put 'deactivate/:id(.:format)', :to => 'users#deactivate', :as => :deactivate_user
  put 'activate/:id(.:format)', :to => 'users#activate', :as => :activate_user
  get 'ckeditor/pictures'
  get '/friends', to: 'friendships#index', as: 'friends'
  get '/news', to: 'news#index', as: 'news'
  get '/newsfeed' , to: 'news#index', as: 'newsfeed'
  root 'conversations#index'  
  get '/posts', to: 'posts#index', as: 'posts'
post 'friends/create/:id', to: 'friendships#create', as: 'add_friend'
put 'friends/accept.:id', to: 'friendships#accept', as: 'accept_request'
delete 'friends/deny/:id', to: 'friendships#deny', as: 'deny_request'
delete 'friends/delete/:id', to: 'friendships#destroy', as: 'delete_friend'

  resources :friendships
  resources :posts do
    resources :comments 
  	resources :likes 
  end
  resources :comments do
  	resources :comments 
  end
  resources :rooms do
    get 'join', :on => :member
    delete 'leave', :on => :member    
  end
  
  resources :memberships, except: [:new]

  resources :events 
  get 'pages/home'
  devise_for :users
  resources :users, only: [:index , :destroy , :show]
  resources :messages, only: [:create , :new]
  resources :conversations, only: [:index, :show , :new]
    
  resources :room_messages
  resources :rooms , except: [:show]
  resources :rooms, only: [:show], shallow: true do
   resources :memberships, only: [:new] #-> domain.com/2/memberships/new
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	enum status: [:requested, :pending, :accepted]
	belongs_to :friend , class_name: 'User'
	def self.request(user, friend)
	unless user == friend
	transaction do
	create(:user => user, :friend => friend, :status => 1)
	create(:user => friend, :friend => user, :status => 0)
	end
	end
	end
	def self.accept(user, friend)
	transaction do
	updated_at = Time.now
	accept_one_side(user, friend, updated_at)
	accept_one_side(friend, user, updated_at)
	end
	end
	def self.breakup(user, friend)
		
	transaction do
	find_by_user_id_and_friend_id(user, friend).destroy
	find_by_user_id_and_friend_id(friend, user).destroy
	end
	end
	private
	def self.accept_one_side(user, friend, updated_at)
	request = find_by_user_id_and_friend_id(user, friend)
	request.status = 2
	request.save!
	end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
before_action :def_user, only: [:create, :accept, :deny, :destroy]


def index
	@users = User.all

@user = current_user
@friends = @user.friends.paginate :page => params[:page]
@pending_friends = @user.pending_friends.paginate :page => params[:page]
@requested_friends = @user.requested_friends.paginate :page => params[:page]
end


def show
@friend = User.find(params[:id])
end

def create
if already_sent_request?
	flash[:notice] = "You already sent the friend request "
else	
Friendship.request(@user1, @friend)
flash[:notice] = "Friend request has been sent to #{@friend.first_name}."
 respond_to do |format|

      format.html  # index.html.erb
      format.js  {  }
    end
end
end

def already_sent_request?
		Friendship.where(user_id: current_user.id, 	friend_id: @friend.id).exists?
	end


def accept
Friendship.accept(@user1, @friend)

flash[:notice] = "Friend request from #{@friend.first_name} has been accepted."
# redirect_to friends_path
	  respond_to do |format|
	  	#format.html
        # index.html.erb
      format.js 
  end
 
end


def deny
	
Friendship.breakup(@user1, @friend)
flash[:notice] = "Friend request from #{@friend.first_name} has been declined."
respond_to do |format|

      format.html  # index.html.erb
      format.js  {  }
    end
 
     
#redirect_to friends_path
end


def destroy

Friendship.breakup(@user1, @friend)
flash[:notice] = "#{@friend.first_name} has been successfully removed from your friends list."
#redirect_to friends_path

respond_to do |format|

      format.html  # index.html.erb
      format.js  {  }
    end

end


private
def def_user

@user1 = current_user
@friend = User.find(params[:id])
end







=begin	def create
	  @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
	  if @friendship.save
	    flash[:notice] = "Added friend."
	    redirect_to root_url
	  else
	    flash[:notice] = "Unable to add friend."
	    redirect_to root_url
	  end
	end
	def destroy
	
	  @friendship = current_user.friendships.find(params[:id])
	  @friendship.destroy
	  flash[:notice] = "Removed friendship."
	  redirect_to current_user
	end
	def show 
		
	end
=end	
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/accept.js.erb
$("#accept_button").click(function(){
    $("#accept_view").hide();
    $('#remove_view').show();
  });

$('#not').html("<%=j render partial: 'layouts/alerts' %>");

app/views/friendships/create.html.erb
create

app/views/friendships/create.js.erb
$('#not').html("<%=j render partial: 'layouts/alerts' %>");

$('#send_req').hide();

app/views/friendships/deny.js.erb
$('#not').html("<%=j render partial: 'layouts/alerts' %>");
$('#deny_req').after("'<%= j render partial: 'friend_list'%>")

app/views/friendships/destroy.js.erb
$('#not').html("<%=j render partial: 'layouts/alerts' %>");

app/views/friendships/index.html.erb
<div id="not">
	
</div>
<div class="panel panel-default">
<%#= render 'friends/lookup' %>
<% if @friends.count > 0 || @requested_friends.count > 0 %>
<h2 align="center" class="panel panel-primary">My Friends</h2>

<table class="table table-striped">
<thread>
<tr>
<th>Name</th>
<th> Request </th>
</tr>
</thread>
<tbody>
	
<% @friends.each do |friend| %>
<tr>
<td><%= friend.first_name %></td>
<td>
	<div id="view_remove">
<%= link_to "View Profile", friendship_path(friend.id) , class:"btn btn-primary btn-xs" %>
<%= link_to 'Remove Friend', deny_request_path(friend), method: :delete, :confirm => "Are you sure?", :class => "btn btn-xs btn-danger" , remote: true %>

  <%= link_to 'send a message', new_message_path(receiver_id: friend.id) , class:"btn btn-primary btn-xs"  %>

</div>
</td>
</tr>
<% end %>
</div>
<% @requested_friends.each do |requested_friend| %>
<tr>
<td><%= requested_friend.first_name %></td>
<td>
	<div id="accept_view">
<%= link_to "View Profile", friendship_path(requested_friend), class:"btn btn-primary btn-xs" %>



	<%= link_to "Accept", accept_request_path(requested_friend), method: :put, class:"btn btn-default btn-xs" , remote: true , id: "accept_req " %>
	<%#= link_to "Accept", accept_request_path(requested_friend), method: :put, class:"btn btn-default btn-xs" , remote: true  %>



<%= link_to "Decline", deny_request_path(requested_friend), method: :delete, class: "btn btn-xs btn-danger" , remote: true %>
</div>
</td>
</tr>
<% end %>
</tbody>
</table>
<% else %>
<p class="lead", align = "center"> You don't have any friends yet. Go out and make some. </p>
<% end %>
</div>
</div>

<div class="container" >
<h3> Add Friends </h3>
<%= render partial: "users/list" %>

</div>

app/views/friendships/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style >
		.card-img-top{
			width: 200px;
		}
	</style>
</head>
<body>
<!-- Section: Personal card -->
<section class="my-5">

  <!-- Grid row -->
  <div class="row">

    <!-- Grid column -->
    <div class="col-md-6 col-lg-4">

      <!-- Card -->
      <div class="card card-personal">

        <!-- Card image-->

       
         <% @friend.avatar.each do |image| %>

        <div class="card-img-top">
        <%= image_tag(image)  %> 
         </div>
         <% end -%>

         <% if @friend.avatar.count == 0 %>
         <h4>  <%=@friend.first_name%> Dont have Profile picture </h4>
         <% end -%>
        <!-- Card image-->

        <!-- Card content -->
        <div class="card-body">
          <!-- Title-->
          <a>
            <h4 class="card-title title-one"><%= @friend.first_name %> <%= @friend.last_name %></h4>
          </a>
          <p class="card-meta">Email : <%= @friend.email %> </p>.

          <p class="card-meta">Date of Birth : <%= @friend.date_of_birth %> </p>

          <p class="card-meta"> <b> Interested In :  </b> </p> <% if @friend.gender == "male"%>  <P> Female </P><% else %>  <p>  Male </p>
          <!-- Text --> 
          <% end -%>
          <p class="card-text"><h3> About Me </h3> </p>
          <div>
          	i need someone to talk 
          </div>
          <hr>
          <a class="card-meta"><span><i class="fas fa-user"></i> No. of Friends  <%= @friend.friends.count %></span></a> <br>

          <a class="card-meta"><span><i class="fas fa-user"></i> No. of Posts posted by <%= @friend.first_name%> <%= @friend.posts.count %></span></a>
          <br>
          <br>

          <span><i class="fas fa-user"> <%= link_to "Back" , friendships_path %> </i>  </span>
          
        </div>
        <!-- Card content -->

      </div>
      <!-- Card -->

    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->

</section>


</body>
</html>

<!-- Section: Personal card -->