config/routes.rb
Rails.application.routes.draw do
  resources :controllers
  mount ActionCable.server, at: '/cable'  
  resources :chatrooms do 
    resource :chatroom_users
    resources :chatroom_messages

  end
  get 'pages/_profile'

  put 'deactivate/:id(.:format)', :to => 'users#deactivate', :as => :deactivate_user
  put 'activate/:id(.:format)', :to => 'users#activate', :as => :activate_user
  get 'ckeditor/pictures'
  get '/friends', to: 'friendships#index', as: 'friends'
  get '/news', to: 'news#index', as: 'news'
  get '/newsfeed' , to: 'news#index', as: 'newsfeed'
  root 'conversations#index'  
  get '/posts', to: 'posts#index', as: 'posts'
post 'friends/create/:id', to: 'friendships#create', as: 'add_friend'
put 'friends/accept.:id', to: 'friendships#accept', as: 'accept_request'
delete 'friends/deny/:id', to: 'friendships#deny', as: 'deny_request'
delete 'friends/delete/:id', to: 'friendships#destroy', as: 'delete_friend'

  resources :friendships
  resources :posts do
    resources :comments 
  	resources :likes 
  end
  resources :comments do
  	resources :comments 
  end
  resources :rooms do
    get 'join', :on => :member
    delete 'leave', :on => :member    
  end
  
  resources :memberships, except: [:new]

  resources :events 
  get 'pages/home'
  devise_for :users
  resources :users, only: [:index , :destroy , :show]
  resources :messages, only: [:create , :new]
  resources :conversations, only: [:index, :show , :new]
    
  resources :room_messages
  resources :rooms , except: [:show]
  resources :rooms, only: [:show], shallow: true do
   resources :memberships, only: [:new] #-> domain.com/2/memberships/new
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
has_many :room_messages, dependent: :destroy,
                         inverse_of: :room
#has_many :friendships, :dependent => :destroy

has_many :memberships, :dependent => :destroy
has_many :users , through: :memberships 


  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :load_entities
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end
  def show
  @room_message = RoomMessage.new room: @room
  @room_messages = @room.room_messages.includes(:user)
  #order("created_at Desc")
  end
  def join
    if already_joined?
      flash[:notice] = "You already in this group"
    else 
    @room = Room.find(params[:id])
    @room.memberships.create(user_id: current_user.id , room_id: @room.id)
    redirect_to rooms_path
  end
  end
  def already_joined?
    Membership.where(user_id: current_user.id, room_id:
      params[:id]).exists?
  end

   def leave
    @room = Room.find(params[:id])
    @room.memberships.find_by(user_id: current_user.id)
    @m.destroy
    respond_to do |format|
      if @m.destroy
        format.html { redirect_to(rooms_path, :notice => 'You leave the group.') }
       
      else
        format.html { redirect_to(@room, :notice => 'leave error.') }

      end
    end
  end

  
 

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name , :user_id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for @room do |form| %>
  <%= form.text_field :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_room_messages.html.erb
<div id="message" >
<%= room_message.message %><br>
                  send by <b style="color: black">
                  <%= room_message.user.first_name %></b>
</div>

app/views/rooms/_rooms.html.erb
<div class="mb-3">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Create a Group
  <% end %>
</div>

<% if @rooms.present? %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
    <div style="display: flex;">
    <div style="width: 25%; height: 10px; padding: 5px;">
      
     <strong > <%= link_to room.name, room_path(room.id) ,class: 'nav-link room-nav-link' %></strong>

     </div>
  

      <%= button_to "Join" , memberships_path(room.id) , method: :post, class: 'btn  btn-default' %>


        <%= button_to "leave" , leave_room_path(room.id), method: :delete , class: 'btn  btn-default' %>

  
     </div>

    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    The are no Groups
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <div class="mb-3">
        <%= render partial: 'rooms' %>
  </div>
</div>
</div>


  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading" >
        Welcome to the social media application!
      </h4>

      <p>
        We need to talk.
      </p>

      <hr />

    </div>
</div>

app/views/rooms/new.html.erb
<h1>
  Creating a room  
</h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<h1>
  <%= @room.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="chat" , id="chat-box">
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container">
          <div class="row no-gutters">
       

            <div class="col">
              <% if current_user.id == room_message.user.id %>
              <div class="message-content pull-right" style="padding: 20px;">
                <p class="mb-1"  >
                 
                  <%= render partial: "room_messages/room_messages" , locals: { room_message: room_message } %>
                  
                  
                </p>

                <div class="text-right">
                  <small>
                    <%= time_ago_in_words(room_message.created_at) %>
                  </small>
                </div>
              </div>
              <% else %>
              <div class="message-content pull-left", style="padding: 20px;">
                <p class="mb-1">
                 
                  <%= render partial: "room_messages/room_messages" , locals: {room_message: room_message } %>
                  
                  
                </p>

                <div class="text-right">
                  <small>
                    <%= time_ago_in_words(room_message.created_at) %>
                  </small>
                </div>
              </div>
              <% end -%>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= form_for @room_message, remote: true do |form| %>
      <div class="input-group mb-3 pull-right">
        <%= form.text_area :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input'
                                 } %>
        <div class="input-group-append ">
          <%= form.submit "Send", class: 'btn btn-primary chat-input'  %>
        </div>
      </div>
      <div style="display: none;">
      <%= form.text_field :room_id, as: :hidden %>
      </div>
    <% end %>
  </div>
</div>